<a href="https://colab.research.google.com/github/alstarian/pytorch/blob/main/Intro_to_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import numpy as np

my_list = [[1,2,3,4,3],  [6,6,7,8,9] ]
my_list

[[1, 2, 3, 4, 3], [6, 6, 7, 8, 9]]

In [12]:
np1 = np.random.rand(3)
np1

array([0.84478065, 0.69318884, 0.41286874])

In [11]:
np1.dtype

dtype('float64')

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.7174, -0.9043, -2.2368,  0.2430],
        [-0.5062, -1.2387,  1.2386,  1.0228],
        [ 0.4090, -0.5658,  0.6512, -0.2689]])

In [15]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])