<a href="https://colab.research.google.com/github/alstarian/pytorch/blob/main/Math_Ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [8]:
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [9]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])