<a href="https://colab.research.google.com/github/alstarian/pytorch/blob/main/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
mytorch2 = torch.arange(12)
mytorch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
mytorch2 = mytorch2.reshape(2,6)
mytorch2

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [32]:
mytorch2[1] = 414
mytorch2

tensor([  0, 414,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [33]:
mytorch3 = mytorch2.reshape(2,6)
mytorch3

tensor([[  0, 414,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11]])

In [34]:
#SLICES

In [36]:
my_torch7 = torch.arange(10)
my_torch7



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
my_torch7[8]

tensor(8)

In [40]:
mytorch8 = my_torch7.reshape(5,2)
mytorch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [41]:
mytorch8[:,1]

tensor([1, 3, 5, 7, 9])

In [42]:
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])